# -*- coding: utf-8 -*-
"""Survival_of_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZYzoNrCGrjHuRrzQ06rxZ0VHMPL1iU8
"""

def calculator():
  x=int(input('Enter your Age:'))

  while True:
    print('''
             Options:
             1)Months
             2)Weeks
             3)Days
             4)Hours
             5)Minutes
             6)Seconds
             7)Exit''')

    choose=int(input('Select Your Option:'))

    if choose == 1:
      months=x*12
      print(f'Your Age in Months is {months} Months')
    elif choose == 2:
      weeks=x*52
      print(f'Your Age in Weeks is {weeks} Weeks')
    elif choose == 3:
      days=x*365
      print(f'Your Age in Days is {days} Days')
    elif choose == 4:
      days=x*365
      hours=days*24
      print(f'Your Age in Hours is {hours} Hours')
    elif choose == 5:
      hours=days*24
      minutes=hours*60
      print(f'Your Age in Minutes is {minutes} Minutes')
    elif choose == 6:
      minutes=hours*60
      seconds=minutes*60
      print(f'Your Age in Seconds is {seconds} Seconds')
    elif choose == 7:
      print('Thank You !!!!')
      break;
    else:
      print('You Have Selected Wrong Option')

calculator()